obstacle_range: 2.5
raytrace_range: 3.0
footprint: [ [0.2, 0.2], [-0.2, 0.2], [-0.2, -0.2], [0.2, -0.2] ]
#robot_radius: ir_of_robot
#robot_radius: 0.5 # distance a circular robot should be clear of the obstacle
inflation_radius: 3.0

observation_sources: point_cloud_sensor

# marking - add obstacle information to cost map
# clearing - clear obstacle information to cost map
laser_scan_sensor: {sensor_frame: frame_name, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

#point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: /camera/depth/image_rect_raw, marking: true, clearing: true}
